insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.31', true, '57 Heath Trail', '651 Memorial Lane', 'abendtsen1j', 1);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.13', true, '578 Sutteridge Lane', '8037 Hovde Road', 'abirt1f', 2);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('17.83', true, '4 Hagan Street', '88917 Stone Corner Parkway', 'afalknerf', 3);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('7.22', true, '3999 Sage Junction', '772 Butterfield Trail', 'afitzsymon13', 4);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.63', false, '13 Grayhawk Plaza', '65 Packers Hill', 'ahallybone1a', 5);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('20.00', false, '72074 Drewry Alley', '52344 Service Drive', 'amckerroww', 6);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.56', false, '9778 Loomis Parkway', '4012 Center Hill', 'ascholar18', 7);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.84', false, '3364 Norway Maple Terrace', '884 Reindahl Road', 'asheircliffe1m', 8);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.05', false, '4145 Elmside Circle', '73211 Bultman Road', 'astreeter2c', 9);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.83', false, '36910 Cottonwood Parkway', '2595 8th Place', 'atomicki29', 10);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.84', false, '6 Arapahoe Pass', '0 8th Park', 'avan14', 11);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.33', true, '81964 Division Court', '04 Monterey Drive', 'bcallinan1b', 12);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('7.48', true, '6 Ludington Avenue', '408 Elgar Terrace', 'bkastingx', 13);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('15.71', true, '3 Meadow Ridge Junction', '077 Pankratz Plaza', 'bsandbrookr', 14);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.21', true, '4704 Starling Lane', '7337 Lawn Lane', 'bstarmonty', 15);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('17.17', false, '01586 Shopko Parkway', '58 Arizona Park', 'btompionm', 16);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('16.58', true, '11 Pond Hill', '21730 Jay Hill', 'btrundler1h', 17);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.25', false, '834 Mayer Center', '81454 Manitowish Center', 'cacuna16', 18);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('7.60', false, '36138 Chinook Alley', '139 Tennessee Drive', 'cchesterfield28', 19);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('15.48', true, '50400 Derek Alley', '795 Petterle Road', 'ccoulthartv', 20);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.87', false, '8551 Dayton Place', '60 Division Point', 'ccrother2k', 21);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('17.49', false, '896 Burrows Terrace', '40 Dunning Crossing', 'ckleingrub26', 22);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('15.30', true, '9 Merrick Street', '807 Brentwood Center', 'cmcmurray1o', 23);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.65', false, '23 Cascade Court', '64498 Lerdahl Hill', 'cspinozzid', 24);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.89', false, '8884 Stoughton Terrace', '17 Esch Road', 'ctreherne6', 25);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.18', true, '8766 Springs Street', '7255 Pearson Junction', 'dfearnehough5', 26);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.85', true, '0 Bultman Street', '4441 Thackeray Crossing', 'dhugo12', 27);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('16.07', true, '75 Westridge Hill', '2 Twin Pines Road', 'dscuddersu', 28);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.07', false, '21 Bunting Pass', '55 Hooker Place', 'ecolclough2e', 29);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.95', true, '865 Garrison Plaza', '69984 Gulseth Point', 'edearnaly1y', 30);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.99', false, '33 Loeprich Parkway', '1 Erie Alley', 'egytesham7', 31);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.16', true, '09 East Parkway', '47015 Delladonna Crossing', 'eloftyi', 32);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.01', false, '2 Grover Trail', '08863 Nova Plaza', 'emaffioni2d', 33);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('7.05', false, '3 Claremont Point', '2 Kennedy Parkway', 'emowling2a', 34);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('16.53', false, '5427 Tomscot Alley', '50479 Pleasure Point', 'etabbitt1t', 35);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.81', true, '32 Corry Road', '6 Hovde Pass', 'fbridgman2o', 36);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.25', false, '5 Debra Terrace', '00 Corscot Parkway', 'fharbor1k', 37);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.48', false, '073 Messerschmidt Lane', '7691 Bartillon Terrace', 'gcockaymee', 38);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.30', true, '4 Jana Avenue', '2253 Doe Crossing Pass', 'gfarndon1p', 39);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.97', true, '79037 Old Gate Hill', '4382 Mayfield Trail', 'gjeanneauh', 40);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.51', false, '5131 Marcy Alley', '26010 Valley Edge Hill', 'grainforthk', 41);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.74', false, '90498 Upham Street', '6686 Sutteridge Road', 'gshankle2f', 42);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.80', true, '6 Waywood Court', '5 Lotheville Lane', 'gstito', 43);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.04', true, '33905 Northport Alley', '9877 Pleasure Plaza', 'gtomalin4', 44);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('16.33', false, '11 Bunker Hill Street', '2 Buhler Point', 'gtort2r', 45);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.12', true, '2546 Autumn Leaf Plaza', '9444 Dapin Alley', 'hnibley1u', 46);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.47', true, '383 Lakewood Gardens Drive', '60196 Twin Pines Point', 'hoddy1e', 47);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('7.96', false, '0518 Mitchell Place', '72 Beilfuss Drive', 'hpinnickz', 48);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('17.72', false, '95580 Brown Trail', '45 Sherman Crossing', 'jhattiganj', 49);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.65', true, '7 Hooker Plaza', '00 Northport Park', 'jwhitington27', 50);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.39', true, '070 Waywood Way', '31 Transport Lane', 'kdeversa', 51);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.70', true, '9113 Sachtjen Point', '5 Truax Court', 'khenriquet24', 52);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.57', false, '64688 Chinook Lane', '989 Vera Court', 'kshacklady1l', 53);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.37', false, '2 Bay Place', '12093 Prentice Court', 'ktrelease10', 54);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('11.52', true, '3507 Warrior Trail', '653 Moland Park', 'lbone1c', 55);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.27', true, '52 Birchwood Center', '58 Havey Pass', 'lfedorski2q', 56);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.62', false, '305 Lotheville Plaza', '60 Lighthouse Bay Road', 'lgodsell15', 57);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.73', false, '8516 Summer Ridge Park', '31400 7th Hill', 'lismay22', 58);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.51', true, '53993 Merry Center', '9 Walton Junction', 'lprisk2b', 59);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.17', true, '994 Union Park', '364 Eagle Crest Circle', 'lsandey11', 60);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.77', false, '3584 Stang Center', '027 Fuller Hill', 'maxlebyn', 61);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.69', true, '620 North Road', '1 School Pass', 'mbainsg', 62);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.09', false, '89234 Trailsway Place', '90006 Declaration Plaza', 'mbewlayt', 63);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('15.32', false, '3 Gulseth Street', '3027 Bultman Pass', 'mdanielou2', 64);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.47', false, '34 Bay Circle', '393 Cambridge Plaza', 'mhawford1q', 65);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('6.69', true, '489 Kensington Crossing', '3873 Esch Way', 'mlantophq', 66);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.24', true, '0240 Scofield Circle', '48 Anthes Park', 'mmannock1d', 67);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.55', true, '13 Randy Point', '07986 Springview Parkway', 'mrikkard2p', 68);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.64', false, '50 Vera Avenue', '1 Golf View Drive', 'mtettersell2h', 69);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('8.75', true, '80857 Forster Road', '5 Hallows Lane', 'mtextonc', 70);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.68', true, '446 Westerfield Place', '1 Johnson Avenue', 'mvasyukhnov0', 71);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('11.76', true, '16888 Oakridge Circle', '60 Warbler Trail', 'ncrannachl', 72);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.85', false, '54486 Welch Pass', '7371 Esker Place', 'nfaint1s', 73);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.56', true, '162 Corscot Street', '75819 Debs Way', 'npetrichat3', 74);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.16', true, '47391 Meadow Valley Lane', '3 Village Plaza', 'nphilipeaup', 75);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.14', true, '75180 Eastlawn Hill', '63981 Corben Center', 'nrumble2i', 76);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.94', true, '0436 Sage Parkway', '794 Delladonna Parkway', 'nshayes9', 77);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.26', false, '281 Ridgeway Place', '7372 Ryan Trail', 'pclementucci1i', 78);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.51', false, '3 Ronald Regan Parkway', '6581 Delaware Avenue', 'pespley2n', 79);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.73', false, '7896 Main Street', '3 Schiller Center', 'rbandiera2m', 80);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('13.48', true, '3 Kingsford Avenue', '6 Barnett Way', 'rpickavance2l', 81);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('16.66', true, '69314 Bartelt Point', '64 Clove Crossing', 'rtongue1z', 82);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.22', false, '3987 Evergreen Court', '03909 Moland Hill', 'scluff1g', 83);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.24', true, '4 Glacier Hill Terrace', '25254 Sauthoff Alley', 'sgravey23', 84);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.16', true, '404 Debra Alley', '0473 Fordem Parkway', 'shebblewaite21', 85);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('11.21', true, '89 Reindahl Junction', '7 Bunker Hill Court', 'skohring1r', 86);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('15.06', false, '8 Talisman Crossing', '162 Quincy Crossing', 'sledley1w', 87);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('10.32', true, '346 Crowley Way', '411 2nd Point', 'slorman25', 88);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.08', false, '86500 Tennessee Drive', '59929 Crownhardt Hill', 'swodham2g', 89);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.25', true, '32 Drewry Drive', '19638 Golf View Park', 'tband1', 90);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.32', true, '98634 Manley Drive', '872 Monica Plaza', 'tdorgan1x', 91);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.85', true, '485 Pond Circle', '5 Scoville Point', 'tfury19', 92);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('9.66', true, '6 Meadow Vale Avenue', '13224 Morning Street', 'tshoorbrooke1n', 93);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('14.00', false, '2574 Division Point', '8988 Judy Alley', 'vdobie2j', 94);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('19.95', false, '14 Shoshone Court', '81459 Talmadge Terrace', 'vfoulstone8', 95);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('11.34', true, '3 Maywood Terrace', '69 Emmet Terrace', 'vphilips17', 96);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.19', false, '3 Oakridge Street', '4832 Hallows Street', 'wfaithfullb', 97);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('18.90', true, '0 Blaine Plaza', '3335 Stephen Parkway', 'wkyngdon1v', 98);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('5.44', false, '337 Moland Circle', '67874 Carey Terrace', 'ykrop20', 99);
insert into user_bid (bidamount, success, passgsrcdest, passgfindest, username, ride_id) values ('12.07', true, '16 Truax Junction', '72 Superior Crossing', 'ymenloes', 100);