/* 
Script info:
This script inserts 100 cars 
*/

insert into car (numPlate, model, brand) values ('SNY 5712E', 'Loyale', 'Subaru');
insert into car (numPlate, model, brand) values ('SAK 5870E', 'C30', 'Volvo');
insert into car (numPlate, model, brand) values ('SSL 9846G', '900', 'Saab');
insert into car (numPlate, model, brand) values ('SWG 3128Y', 'Montana', 'Pontiac');
insert into car (numPlate, model, brand) values ('SME 1196U', 'IS', 'Lexus');
insert into car (numPlate, model, brand) values ('SOW 4397Q', 'Cutlass', 'Oldsmobile');
insert into car (numPlate, model, brand) values ('SPC 2824M', 'F250', 'Ford');
insert into car (numPlate, model, brand) values ('SJZ 1204A', 'Hombre Space', 'Isuzu');
insert into car (numPlate, model, brand) values ('SPH 3881A', 'F250', 'Ford');
insert into car (numPlate, model, brand) values ('SOL 7098I', 'Canyon', 'GMC');
insert into car (numPlate, model, brand) values ('SBQ 4746R', 'Neon', 'Dodge');
insert into car (numPlate, model, brand) values ('SBA 6302R', 'Neon', 'Dodge');
insert into car (numPlate, model, brand) values ('SSA 1547Q', 'Samurai', 'Suzuki');
insert into car (numPlate, model, brand) values ('SOD 4978Y', 'Titan', 'Nissan');
insert into car (numPlate, model, brand) values ('SNU 6997E', 'Brat', 'Subaru');
insert into car (numPlate, model, brand) values ('SUB 0398X', 'Sephia', 'Kia');
insert into car (numPlate, model, brand) values ('SXW 2148Q', 'Corvette', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SRO 3535A', 'Galant', 'Mitsubishi');
insert into car (numPlate, model, brand) values ('SRA 1477W', 'Millenia', 'Mazda');
insert into car (numPlate, model, brand) values ('SYW 5888Z', 'Grand Marquis', 'Mercury');
insert into car (numPlate, model, brand) values ('SNS 6900O', 'Yukon XL 2500', 'GMC');
insert into car (numPlate, model, brand) values ('SNM 3281Q', 'Ascender', 'Isuzu');
insert into car (numPlate, model, brand) values ('SXX 7054W', '2500 Club Coupe', 'GMC');
insert into car (numPlate, model, brand) values ('SNV 3909G', 'Contour', 'Ford');
insert into car (numPlate, model, brand) values ('SFQ 8162Y', 'Silverado 2500', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SND 4497J', 'Ram 1500 Club', 'Dodge');
insert into car (numPlate, model, brand) values ('SPY 3754Y', 'ES', 'Lexus');
insert into car (numPlate, model, brand) values ('SCG 7446Y', 'SC', 'Lexus');
insert into car (numPlate, model, brand) values ('SVP 6726O', 'Yukon', 'GMC');
insert into car (numPlate, model, brand) values ('STZ 8552M', 'Range Rover', 'Land Rover');
insert into car (numPlate, model, brand) values ('SJM 6531V', 'LeSabre', 'Buick');
insert into car (numPlate, model, brand) values ('SIR 9380Y', 'E-Series', 'Ford');
insert into car (numPlate, model, brand) values ('SRL 8176I', 'Range Rover Sport', 'Land Rover');
insert into car (numPlate, model, brand) values ('SKV 0229G', 'Grand Vitara', 'Suzuki');
insert into car (numPlate, model, brand) values ('SII 8746A', 'Corolla', 'Toyota');
insert into car (numPlate, model, brand) values ('SOG 0797O', 'Sonata', 'Hyundai');
insert into car (numPlate, model, brand) values ('SOK 5443D', 'GT-R', 'Nissan');
insert into car (numPlate, model, brand) values ('SXN 9135V', 'Town Car', 'Lincoln');
insert into car (numPlate, model, brand) values ('SXN 7085S', 'Grand Prix', 'Pontiac');
insert into car (numPlate, model, brand) values ('SLC 2512F', 'Range Rover', 'Land Rover');
insert into car (numPlate, model, brand) values ('SPS 5465G', 'Continental', 'Lincoln');
insert into car (numPlate, model, brand) values ('SGE 4655K', 'tC', 'Scion');
insert into car (numPlate, model, brand) values ('SCJ 5296D', 'Spyder', 'Maserati');
insert into car (numPlate, model, brand) values ('SNR 6694B', 'Endeavor', 'Mitsubishi');
insert into car (numPlate, model, brand) values ('SIT 8352Q', 'GTI', 'Volkswagen');
insert into car (numPlate, model, brand) values ('SLL 7968O', 'SX4', 'Suzuki');
insert into car (numPlate, model, brand) values ('SHM 6456D', '98', 'Oldsmobile');
insert into car (numPlate, model, brand) values ('SDC 4722P', '911', 'Porsche');
insert into car (numPlate, model, brand) values ('SRQ 0594D', 'Sundance', 'Plymouth');
insert into car (numPlate, model, brand) values ('SSP 9765P', 'Fillmore', 'Fillmore');
insert into car (numPlate, model, brand) values ('SOA 0831P', 'SVX', 'Subaru');
insert into car (numPlate, model, brand) values ('SRJ 6385I', 'Land Cruiser', 'Toyota');
insert into car (numPlate, model, brand) values ('STZ 7956W', 'Murciélago', 'Lamborghini');
insert into car (numPlate, model, brand) values ('SRZ 4644A', 'XT', 'Subaru');
insert into car (numPlate, model, brand) values ('SZG 2051C', 'Sportvan G10', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SSU 5266V', 'Suburban', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SRI 5510H', 'Matrix', 'Toyota');
insert into car (numPlate, model, brand) values ('SVL 9658Q', 'E250', 'Ford');
insert into car (numPlate, model, brand) values ('SEW 4417G', 'Sunbird', 'Pontiac');
insert into car (numPlate, model, brand) values ('SPO 1791V', 'Countryman', 'MINI');
insert into car (numPlate, model, brand) values ('SDR 4764L', 'DeVille', 'Cadillac');
insert into car (numPlate, model, brand) values ('SNL 7324B', 'Q7', 'Audi');
insert into car (numPlate, model, brand) values ('SZY 0682T', 'Grand Cherokee', 'Jeep');
insert into car (numPlate, model, brand) values ('SPH 2039T', 'MX-5', 'Mazda');
insert into car (numPlate, model, brand) values ('SJL 7201Y', 'DeVille', 'Cadillac');
insert into car (numPlate, model, brand) values ('SWI 2932H', 'Savana 3500', 'GMC');
insert into car (numPlate, model, brand) values ('SJS 8294Q', 'Q', 'Infiniti');
insert into car (numPlate, model, brand) values ('STZ 3404Z', 'B-Series Plus', 'Mazda');
insert into car (numPlate, model, brand) values ('SMR 8747R', '5 Series', 'BMW');
insert into car (numPlate, model, brand) values ('SMS 8988G', 'E-Class', 'Mercedes-Benz');
insert into car (numPlate, model, brand) values ('SRY 5711Y', 'ES', 'Lexus');
insert into car (numPlate, model, brand) values ('SKC 0692P', '9000', 'Saab');
insert into car (numPlate, model, brand) values ('SBF 5061X', 'Mazda3', 'Mazda');
insert into car (numPlate, model, brand) values ('SFB 1829I', 'Ranger', 'Ford');
insert into car (numPlate, model, brand) values ('SKW 7529A', 'XG350', 'Hyundai');
insert into car (numPlate, model, brand) values ('SDJ 8071J', 'Tribute', 'Mazda');
insert into car (numPlate, model, brand) values ('SYB 1750Q', 'Colt', 'Dodge');
insert into car (numPlate, model, brand) values ('SCL 1061P', 'MKX', 'Lincoln');
insert into car (numPlate, model, brand) values ('SKR 6257B', 'H1', 'Hummer');
insert into car (numPlate, model, brand) values ('SQP 8322R', 'Truck', 'Mitsubishi');
insert into car (numPlate, model, brand) values ('SOV 3807R', 'Camaro', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SNQ 5332M', 'Tahoe', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SLR 4787F', 'CR-V', 'Honda');
insert into car (numPlate, model, brand) values ('SWG 8550U', 'Paseo', 'Toyota');
insert into car (numPlate, model, brand) values ('SYD 3698H', 'Silverado 2500', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SNT 6798C', 'CLK-Class', 'Mercedes-Benz');
insert into car (numPlate, model, brand) values ('SVG 4581K', 'V50', 'Volvo');
insert into car (numPlate, model, brand) values ('SGP 7759T', 'Avalanche', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SRC 0862G', 'Pathfinder', 'Nissan');
insert into car (numPlate, model, brand) values ('SRO 6780U', 'S-Series', 'Saturn');
insert into car (numPlate, model, brand) values ('SEO 7661N', 'Familia', 'Mazda');
insert into car (numPlate, model, brand) values ('SBF 5612M', 'Grand Prix', 'Pontiac');
insert into car (numPlate, model, brand) values ('SBT 8734F', 'Navigator L', 'Lincoln');
insert into car (numPlate, model, brand) values ('SUG 5887X', 'Sportvan G30', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SPC 9811W', 'MPV', 'Mazda');
insert into car (numPlate, model, brand) values ('SMJ 7083J', 'Express 1500', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SOP 1570S', 'SLR McLaren', 'Mercedes-Benz');
insert into car (numPlate, model, brand) values ('SMQ 6503E', 'Boxster', 'Porsche');
insert into car (numPlate, model, brand) values ('SQA 1361Q', 'Corvette', 'Chevrolet');
insert into car (numPlate, model, brand) values ('SUX 0042O', 'Cherokee', 'Jeep');
