insert into car (numPlate, brand, model) values ('SWU 8251J', 'Toyota', 'Sienna');
insert into car (numPlate, brand, model) values ('SLW 3290U', 'Subaru', 'Impreza');
insert into car (numPlate, brand, model) values ('SCO 9817X', 'Lincoln', 'Town Car');
insert into car (numPlate, brand, model) values ('SOT 4379M', 'Volkswagen', 'R32');
insert into car (numPlate, brand, model) values ('SLV 3234W', 'Acura', 'NSX');
insert into car (numPlate, brand, model) values ('SMN 1683Q', 'Ford', 'Mustang');
insert into car (numPlate, brand, model) values ('SCJ 5199A', 'BMW', '5 Series');
insert into car (numPlate, brand, model) values ('SON 9660O', 'Porsche', '911');
insert into car (numPlate, brand, model) values ('SNT 6773C', 'Chrysler', 'Crossfire');
insert into car (numPlate, brand, model) values ('SLU 9287H', 'Isuzu', 'i-350');
insert into car (numPlate, brand, model) values ('SGL 2682Z', 'Ford', 'Thunderbird');
insert into car (numPlate, brand, model) values ('SHB 5910A', 'Cadillac', 'Escalade');
insert into car (numPlate, brand, model) values ('SSS 2317F', 'Audi', 'A3');
insert into car (numPlate, brand, model) values ('SZW 2869W', 'Ford', 'F350');
insert into car (numPlate, brand, model) values ('SJF 5800S', 'Cadillac', 'SRX');
insert into car (numPlate, brand, model) values ('SDK 3363J', 'Eagle', 'Summit');
insert into car (numPlate, brand, model) values ('SDN 0781W', 'Chevrolet', 'Astro');
insert into car (numPlate, brand, model) values ('SDS 0263U', 'Chrysler', 'PT Cruiser');
insert into car (numPlate, brand, model) values ('SXJ 1067U', 'Chevrolet', 'Avalanche');
insert into car (numPlate, brand, model) values ('SJB 6804I', 'Nissan', 'Xterra');
insert into car (numPlate, brand, model) values ('SLS 2764Z', 'Dodge', 'Journey');
insert into car (numPlate, brand, model) values ('SSW 0647R', 'Isuzu', 'Space');
insert into car (numPlate, brand, model) values ('STC 1860I', 'Audi', 'A8');
insert into car (numPlate, brand, model) values ('SNX 2020K', 'Nissan', '240SX');
insert into car (numPlate, brand, model) values ('SBM 0744P', 'Cadillac', 'XLR');
insert into car (numPlate, brand, model) values ('SDL 7875Y', 'Mitsubishi', 'L300');
insert into car (numPlate, brand, model) values ('SGD 1681N', 'MINI', 'Cooper');
insert into car (numPlate, brand, model) values ('SVT 8367X', 'Ford', 'F450');
insert into car (numPlate, brand, model) values ('SIY 1998W', 'Audi', 'S4');
insert into car (numPlate, brand, model) values ('SJJ 5083S', 'Pontiac', 'Grand Am');
insert into car (numPlate, brand, model) values ('SGD 3054I', 'Acura', 'NSX');
insert into car (numPlate, brand, model) values ('SDT 3870N', 'Lincoln', 'LS');
insert into car (numPlate, brand, model) values ('SXZ 3747X', 'Mazda', '323');
insert into car (numPlate, brand, model) values ('SRM 6041L', 'Hyundai', 'Azera');
insert into car (numPlate, brand, model) values ('SSA 3833Z', 'Ford', 'Fairlane');
insert into car (numPlate, brand, model) values ('SSO 1058Z', 'Maserati', 'GranSport');
insert into car (numPlate, brand, model) values ('SVS 9649V', 'Buick', 'Park Avenue');
insert into car (numPlate, brand, model) values ('SKN 7218M', 'Ford', 'LTD');
insert into car (numPlate, brand, model) values ('SHN 9616Q', 'Cadillac', 'DTS');
insert into car (numPlate, brand, model) values ('SCR 2580F', 'Mitsubishi', 'Chariot');
insert into car (numPlate, brand, model) values ('SWT 9275F', 'Kia', 'Sedona');
insert into car (numPlate, brand, model) values ('SCZ 3069Y', 'Mazda', '929');
insert into car (numPlate, brand, model) values ('SIV 8539M', 'BMW', 'M5');
insert into car (numPlate, brand, model) values ('SLI 0654E', 'Bentley', 'Continental Flying Spur');
insert into car (numPlate, brand, model) values ('SYE 9413O', 'Nissan', 'Murano');
insert into car (numPlate, brand, model) values ('SXI 9033H', 'Dodge', 'Dakota Club');
insert into car (numPlate, brand, model) values ('STX 8816D', 'Ford', 'Freestar');
insert into car (numPlate, brand, model) values ('STC 0551G', 'Spyker', 'C8');
insert into car (numPlate, brand, model) values ('SJZ 8329A', 'Isuzu', 'Trooper');
insert into car (numPlate, brand, model) values ('SFI 4635R', 'Ford', 'Laser');
insert into car (numPlate, brand, model) values ('SVO 1594O', 'Volkswagen', 'Touareg');
insert into car (numPlate, brand, model) values ('SWM 0645D', 'Land Rover', 'Range Rover');
insert into car (numPlate, brand, model) values ('SMB 4030N', 'Audi', 'Q5');
insert into car (numPlate, brand, model) values ('SWP 8266V', 'Lexus', 'ES');
insert into car (numPlate, brand, model) values ('SMQ 2675O', 'Toyota', 'MR2');
insert into car (numPlate, brand, model) values ('SGQ 0623Z', 'Mitsubishi', 'Endeavor');
insert into car (numPlate, brand, model) values ('SJG 5633N', 'Chevrolet', 'Impala');
insert into car (numPlate, brand, model) values ('SHX 4118N', 'Infiniti', 'I');
insert into car (numPlate, brand, model) values ('SXB 1093R', 'Saab', '9000');
insert into car (numPlate, brand, model) values ('SVQ 0324H', 'Honda', 'Civic Si');
insert into car (numPlate, brand, model) values ('SYC 8798K', 'Land Rover', 'LR2');
insert into car (numPlate, brand, model) values ('SJA 3875W', 'Nissan', 'Pathfinder');
insert into car (numPlate, brand, model) values ('STZ 9695D', 'Lotus', 'Esprit');
insert into car (numPlate, brand, model) values ('SIM 8904X', 'Alfa Romeo', 'Spider');
insert into car (numPlate, brand, model) values ('SWN 1400I', 'GMC', 'Vandura G1500');
insert into car (numPlate, brand, model) values ('SYW 0627A', 'Toyota', 'Tercel');
insert into car (numPlate, brand, model) values ('SZN 7949S', 'Volvo', 'S80');
insert into car (numPlate, brand, model) values ('SAV 4375Q', 'Chevrolet', 'Suburban 2500');
insert into car (numPlate, brand, model) values ('SRY 5389P', 'Ford', 'Windstar');
insert into car (numPlate, brand, model) values ('SSS 7575P', 'Subaru', 'Brat');
insert into car (numPlate, brand, model) values ('SIB 4983R', 'Dodge', 'Ram 2500 Club');
insert into car (numPlate, brand, model) values ('SWL 7198T', 'Toyota', 'Celica');
insert into car (numPlate, brand, model) values ('SZD 9838Q', 'Volvo', '850');
insert into car (numPlate, brand, model) values ('SOS 5955S', 'BMW', 'Z4');
insert into car (numPlate, brand, model) values ('SYY 2778J', 'Jensen', 'Interceptor');
insert into car (numPlate, brand, model) values ('SUP 4669H', 'Chrysler', 'LHS');
insert into car (numPlate, brand, model) values ('SJK 0907J', 'Dodge', 'Ram');
insert into car (numPlate, brand, model) values ('SMP 2466B', 'Nissan', 'Pathfinder');
insert into car (numPlate, brand, model) values ('SPA 5138Y', 'Chevrolet', 'Aveo');
insert into car (numPlate, brand, model) values ('SMP 6565U', 'Chevrolet', 'Cruze');
insert into car (numPlate, brand, model) values ('SVB 7358K', 'MINI', 'Cooper');
insert into car (numPlate, brand, model) values ('SJD 2341Y', 'Ford', 'E-Series');
insert into car (numPlate, brand, model) values ('SCJ 4532V', 'Hillman', 'Minx Magnificent');
insert into car (numPlate, brand, model) values ('SUK 3547G', 'Lotus', 'Esprit');
insert into car (numPlate, brand, model) values ('SKQ 4665O', 'Dodge', 'Dakota Club');
insert into car (numPlate, brand, model) values ('SZT 1922T', 'Honda', 'Accord');
insert into car (numPlate, brand, model) values ('SMV 1480Y', 'Mercedes-Benz', 'W126');
insert into car (numPlate, brand, model) values ('SQA 2934N', 'BMW', '7 Series');
insert into car (numPlate, brand, model) values ('SIC 5223K', 'Acura', 'TSX');
insert into car (numPlate, brand, model) values ('SMT 8008Z', 'Hummer', 'H3');
insert into car (numPlate, brand, model) values ('SYI 9784I', 'Lexus', 'IS');
insert into car (numPlate, brand, model) values ('SVA 6272N', 'Suzuki', 'Swift');
insert into car (numPlate, brand, model) values ('SUG 3961N', 'Mitsubishi', 'Mirage');
insert into car (numPlate, brand, model) values ('SDV 3323W', 'GMC', 'Yukon');
insert into car (numPlate, brand, model) values ('SEC 9731P', 'Pontiac', 'G5');
insert into car (numPlate, brand, model) values ('SLS 0726B', 'BMW', '760');
insert into car (numPlate, brand, model) values ('SEF 7513A', 'Kia', 'Sorento');
insert into car (numPlate, brand, model) values ('SEE 5289Q', 'Nissan', '350Z');
insert into car (numPlate, brand, model) values ('SIZ 4692W', 'Pontiac', 'GTO');
insert into car (numPlate, brand, model) values ('STC 5538Q', 'Audi', 'A8');
